# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Designs/addCoursePageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyodbc
import os
class Ui_MainWindow(object):
        def home(self):
                os.system("python landingPageUI.py")
        def submitPressed(self):
                id = self.takeCourseID.toPlainText()
                hours = self.takeCourseHrs.value()
                cName = self.takeCourseName.toPlainText()

                # Set your SQL Server connection parameters
                server = 'DESKTOP-03OJGVQ\SQLEXPRESS'
                database = 'myCollege'
                trusted_connection = 'yes'
                driver = '{ODBC Driver 17 for SQL Server}'  # Adjust the driver based on your SQL Server version

                        # Create a connection string
                connection_string = f"DRIVER={driver};SERVER={server};DATABASE={database};Trusted_Connection={trusted_connection}"

                        # Establish a connection
                with pyodbc.connect(connection_string) as connection:
                        cursor = connection.cursor()

                                # Use parameterized query to prevent SQL injection
                        insert_query = "INSERT INTO [dbo].[Course]([courseID],[courseName],[courseCreditHr])VALUES (?, ?, ?)"

                                # Provide values directly in the execute call
                        cursor.execute(insert_query, id, cName, int(hours))
                        connection.commit()


                        connection.close()

        
        def clearButton(self):
               self.takeCourseID.clear()
               self.takeCourseHrs.setValue(0)
               self.takeCourseName.clear()
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(800, 600)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
                self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
                self.gridLayoutWidget.setObjectName("gridLayoutWidget")
                self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
                self.gridLayout.setContentsMargins(0, 0, 0, 0)
                self.gridLayout.setObjectName("gridLayout")
                self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
                self.frame.setAutoFillBackground(False)
                self.frame.setStyleSheet(" background-color: #345687;")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.label_4 = QtWidgets.QLabel(self.frame)
                self.label_4.setGeometry(QtCore.QRect(290, 10, 211, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("font-size: 40px;\n"
        "color: white;")
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.frame)
                self.label_5.setGeometry(QtCore.QRect(300, 90, 181, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_5.setFont(font)
                self.label_5.setStyleSheet("font-size: 30px;\n"
        "color: white;")
                self.label_5.setObjectName("label_5")
                self.takeCourseID = QtWidgets.QTextEdit(self.frame)
                self.takeCourseID.setGeometry(QtCore.QRect(370, 180, 301, 41))
                self.takeCourseID.setStyleSheet("background-color:white;color:black;font-size:25px;")
                self.takeCourseID.setObjectName("takeCourseID")
                self.label_6 = QtWidgets.QLabel(self.frame)
                self.label_6.setGeometry(QtCore.QRect(130, 180, 161, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_6.setFont(font)
                self.label_6.setStyleSheet("font-size: 30px;\n"
        "color: white;")
                self.label_6.setObjectName("label_6")
                self.label_7 = QtWidgets.QLabel(self.frame)
                self.label_7.setGeometry(QtCore.QRect(130, 250, 201, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_7.setFont(font)
                self.label_7.setStyleSheet("font-size: 30px;\n"
        "color: white;")
                self.label_7.setObjectName("label_7")
                self.takeCourseName = QtWidgets.QTextEdit(self.frame)
                self.takeCourseName.setGeometry(QtCore.QRect(370, 250, 301, 41))
                self.takeCourseName.setStyleSheet("background-color:white;color:black;font-size:25px;")
                self.takeCourseName.setObjectName("takeCourseName")
                self.label_8 = QtWidgets.QLabel(self.frame)
                self.label_8.setGeometry(QtCore.QRect(130, 320, 291, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_8.setFont(font)
                self.label_8.setStyleSheet("font-size: 30px;\n"
        "color: white;")
                self.label_8.setObjectName("label_8")
                self.takeCourseHrs = QtWidgets.QSpinBox(self.frame)
                self.takeCourseHrs.setGeometry(QtCore.QRect(440, 330, 81, 41))
                self.takeCourseHrs.setStyleSheet("background-color:white;font-size:32px")
                self.takeCourseHrs.setObjectName("takeCourseHrs")
                self.submitAddCourseButton = QtWidgets.QPushButton(self.frame)
                self.submitAddCourseButton.setGeometry(QtCore.QRect(430, 410, 111, 51))
                self.submitAddCourseButton.clicked.connect(self.submitPressed)
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.submitAddCourseButton.setFont(font)
                self.submitAddCourseButton.setStyleSheet("background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 20px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid green;")
                self.submitAddCourseButton.setObjectName("submitAddCourseButton")
                self.clearAddCourseButton = QtWidgets.QPushButton(self.frame)
                self.clearAddCourseButton.setGeometry(QtCore.QRect(240, 410, 111, 51))
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.clearAddCourseButton.setFont(font)
                self.clearAddCourseButton.setStyleSheet("background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 20px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid red;")
                self.clearAddCourseButton.setObjectName("clearAddCourseButton")
                self.clearAddCourseButton.clicked.connect(self.clearButton)
                self.homeAddCourseButton = QtWidgets.QPushButton(self.frame)
                self.homeAddCourseButton.clicked.connect(self.home)
                self.homeAddCourseButton.setGeometry(QtCore.QRect(10, 10, 141, 61))
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.homeAddCourseButton.setFont(font)
                self.homeAddCourseButton.setStyleSheet("background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 30px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid green;")
                self.homeAddCourseButton.setObjectName("homeAddCourseButton")
                self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
                MainWindow.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_4.setText(_translate("MainWindow", "My College"))
                self.label_5.setText(_translate("MainWindow", "Add Course"))
                self.label_6.setText(_translate("MainWindow", "Course ID"))
                self.label_7.setText(_translate("MainWindow", "Course Name"))
                self.label_8.setText(_translate("MainWindow", "Course Credit Hrs."))
                self.submitAddCourseButton.setText(_translate("MainWindow", "Submit"))
                self.clearAddCourseButton.setText(_translate("MainWindow", "Clear"))
                self.homeAddCourseButton.setText(_translate("MainWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
