# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Designs/addStudentLandingPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import pyodbc
import os
from addStudentSuccessPageUI import AddStudentSuccessfullPage
class AddStudentLandingPage(object):

        def addStudentSubmitPressed(self):
                id = self.takeStudentID.toPlainText()
                name = self.takeStudentName.toPlainText()
                depart = self.takeStudentDepart.toPlainText()
                age = self.takeStudentAge.value()
                
                if self.takeStudentGenderMale.isChecked():
                        gender = 'M'
                else:
                        gender = 'F'
                
                if(id != ''):
                        

                        # Set your SQL Server connection parameters
                        server = 'DESKTOP-03OJGVQ\SQLEXPRESS'
                        database = 'myCollege'
                        trusted_connection = 'yes'
                        driver = '{ODBC Driver 17 for SQL Server}'  # Adjust the driver based on your SQL Server version

                        # Create a connection string
                        connection_string = f"DRIVER={driver};SERVER={server};DATABASE={database};Trusted_Connection={trusted_connection}"

                        # Establish a connection
                        with pyodbc.connect(connection_string) as connection:
                                cursor = connection.cursor()

                                # Use parameterized query to prevent SQL injection
                                insert_query = "INSERT INTO [dbo].[Student] ([studentID], [studentName], [studentAge], [studentGender], [studentDept]) VALUES (?, ?, ?, ?, ?)"

                                # Provide values directly in the execute call
                                cursor.execute(insert_query, int(id), name, int(age), gender, depart)
                                connection.commit()


                        connection.close()

                        print("Data Transfered!")
                        self.window = QtWidgets.QMainWindow()
                        self.ui = AddStudentSuccessfullPage()
                        self.ui.setupUi(self.window)
                        self.window.show()
                else:
                        # Create an error QMessageBox
                        error_dialog = QMessageBox()
                        error_dialog.setIcon(QMessageBox.Critical)
                        error_dialog.setWindowTitle("Error")
                        error_dialog.setText("Please Fill All The Details.\nID must be integer.")
                        error_dialog.setStandardButtons(QMessageBox.Ok)

                        # Show the error dialog
                        error_dialog.exec_()
                        print("Fill out details please!")
                        
        
        def addStudentClearPressed(self):
                self.takeStudentID.clear()
                self.takeStudentAge.setValue(0)
                self.takeStudentGenderMale.setChecked(False)
                self.takeStudentGenderFemale.setChecked(False)
                self.takeStudentName.clear()
                self.takeStudentDepart.clear()
        
        def homeButton(self):
                os.system("python landingPageUI.py")

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(800, 615)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
                self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
                self.gridLayoutWidget.setObjectName("gridLayoutWidget")
                self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
                self.gridLayout.setContentsMargins(0, 0, 0, 0)
                self.gridLayout.setObjectName("gridLayout")
                self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
                self.frame.setAutoFillBackground(False)
                self.frame.setStyleSheet(" background-color: #345687;")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.label_4 = QtWidgets.QLabel(self.frame)
                self.label_4.setGeometry(QtCore.QRect(290, 10, 211, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("font-size: 40px;\n"
        "color: white;")
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.frame)
                self.label_5.setGeometry(QtCore.QRect(300, 90, 181, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_5.setFont(font)
                self.label_5.setStyleSheet("font-size: 30px;\n"
        "color: white;")
                self.label_5.setObjectName("label_5")
                self.takeStudentID = QtWidgets.QTextEdit(self.frame)
                self.takeStudentID.setGeometry(QtCore.QRect(370, 180, 301, 41))
                self.takeStudentID.setStyleSheet("background-color:white;color:black;font-size:25px;")
                self.takeStudentID.setObjectName("takeStudentID")
                self.label_6 = QtWidgets.QLabel(self.frame)
                self.label_6.setGeometry(QtCore.QRect(130, 180, 161, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_6.setFont(font)
                self.label_6.setStyleSheet("font-size: 30px;\n"
        "color: white;")
                self.label_6.setObjectName("label_6")
                self.label_7 = QtWidgets.QLabel(self.frame)
                self.label_7.setGeometry(QtCore.QRect(130, 250, 201, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_7.setFont(font)
                self.label_7.setStyleSheet("font-size: 30px;\n"
        "color: white;")
                self.label_7.setObjectName("label_7")
                self.takeStudentName = QtWidgets.QTextEdit(self.frame)
                self.takeStudentName.setGeometry(QtCore.QRect(370, 250, 301, 41))
                self.takeStudentName.setStyleSheet("background-color:white;color:black;font-size:25px;")
                self.takeStudentName.setObjectName("takeStudentName")
                self.label_8 = QtWidgets.QLabel(self.frame)
                self.label_8.setGeometry(QtCore.QRect(130, 320, 191, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_8.setFont(font)
                self.label_8.setStyleSheet("font-size: 30px;\n"
        "color: white;")
                self.label_8.setObjectName("label_8")
                self.label_9 = QtWidgets.QLabel(self.frame)
                self.label_9.setGeometry(QtCore.QRect(130, 390, 231, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_9.setFont(font)
                self.label_9.setStyleSheet("font-size: 30px;\n"
        "color: white;")
                self.label_9.setObjectName("label_9")
                self.label_10 = QtWidgets.QLabel(self.frame)
                self.label_10.setGeometry(QtCore.QRect(130, 450, 201, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_10.setFont(font)
                self.label_10.setStyleSheet("font-size: 30px;\n"
        "color: white;")
                self.label_10.setObjectName("label_10")
                self.takeStudentDepart = QtWidgets.QTextEdit(self.frame)
                self.takeStudentDepart.setGeometry(QtCore.QRect(370, 460, 301, 41))
                self.takeStudentDepart.setStyleSheet("background-color:white;color:black;font-size:25px;")
                self.takeStudentDepart.setObjectName("takeStudentDepart")
                self.takeStudentAge = QtWidgets.QSpinBox(self.frame)
                self.takeStudentAge.setGeometry(QtCore.QRect(370, 330, 81, 41))
                self.takeStudentAge.setStyleSheet("background-color:white;font-size:32px")
                self.takeStudentAge.setObjectName("takeStudentAge")
                self.takeStudentGenderMale = QtWidgets.QRadioButton(self.frame)
                self.takeStudentGenderMale.setGeometry(QtCore.QRect(370, 400, 81, 31))
                self.takeStudentGenderMale.setStyleSheet("color:white;font-size:25px")
                self.takeStudentGenderMale.setObjectName("takeStudentGenderMale")
                self.takeStudentGenderFemale = QtWidgets.QRadioButton(self.frame)
                self.takeStudentGenderFemale.setGeometry(QtCore.QRect(480, 400, 101, 31))
                self.takeStudentGenderFemale.setStyleSheet("color:white;font-size:25px")
                self.takeStudentGenderFemale.setObjectName("takeStudentGenderFemale")
                self.submitAddStudent = QtWidgets.QPushButton(self.frame)
                self.submitAddStudent.setGeometry(QtCore.QRect(450, 530, 111, 51))
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.submitAddStudent.setFont(font)
                self.submitAddStudent.clicked.connect(self.addStudentSubmitPressed)
                self.submitAddStudent.setStyleSheet("background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 20px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid green;")
                self.submitAddStudent.setObjectName("submitAddStudent")
                self.clearAddStudent = QtWidgets.QPushButton(self.frame)
                self.clearAddStudent.setGeometry(QtCore.QRect(260, 530, 111, 51))
                self.clearAddStudent.clicked.connect(self.addStudentClearPressed)
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.clearAddStudent.setFont(font)
                self.clearAddStudent.setStyleSheet("background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 20px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid red;")
                self.clearAddStudent.setObjectName("clearAddStudent")
                self.homeAddStudentButton = QtWidgets.QPushButton(self.frame)
                self.homeAddStudentButton.setGeometry(QtCore.QRect(10, 10, 141, 61))
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.homeAddStudentButton.setFont(font)
                self.homeAddStudentButton.clicked.connect(self.homeButton)
                self.homeAddStudentButton.setStyleSheet("background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 30px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid green;")
                self.homeAddStudentButton.setObjectName("homeAddStudentButton")
                self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
                MainWindow.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_4.setText(_translate("MainWindow", "My College"))
                self.label_5.setText(_translate("MainWindow", "Add Student"))
                self.label_6.setText(_translate("MainWindow", "Student ID"))
                self.label_7.setText(_translate("MainWindow", "Student Name"))
                self.label_8.setText(_translate("MainWindow", "Student Age"))
                self.label_9.setText(_translate("MainWindow", "Student Gender"))
                self.label_10.setText(_translate("MainWindow", "Student Dept."))
                self.takeStudentGenderMale.setText(_translate("MainWindow", "Male"))
                self.takeStudentGenderFemale.setText(_translate("MainWindow", "Female"))
                self.submitAddStudent.setText(_translate("MainWindow", "Submit"))
                self.clearAddStudent.setText(_translate("MainWindow", "Clear"))
                self.homeAddStudentButton.setText(_translate("MainWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = AddStudentLandingPage()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
