# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Designs/courseViewAllCoursesUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
import pyodbc
from PyQt5.QtSql import QSqlDatabase, QSqlQueryModel, QSqlQuery
import sys 
import os
class Ui_MainWindow(object):
    def home(self):
        os.system("python landingPageUI.py")
    def loadData(self):
        server = 'DESKTOP-03OJGVQ\SQLEXPRESS'
        database = 'myCollege'
        trusted_connection = 'yes'
        driver = '{ODBC Driver 17 for SQL Server}'  # Adjust the driver based on your SQL Server version

                        # Create a connection string
        connection_string = f"DRIVER={driver};SERVER={server};DATABASE={database};Trusted_Connection={trusted_connection}"
        with pyodbc.connect(connection_string) as connection:
                        
                cursor = connection.cursor()

                #Problem Starts
                self.showCoursesTable.setColumnWidth(0,100)
                self.showCoursesTable.setColumnWidth(1,350)
                self.showCoursesTable.setColumnWidth(2,105)
                self.showCoursesTable.setHorizontalHeaderLabels(["Course ID","Course Name","Course Credit Hrs"])
                query = "select * from Course"
                self.showCoursesTable.setRowCount(50)
                tableIndex = 0
                for row in cursor.execute(query):
                        self.showCoursesTable.setItem(tableIndex,0,QtWidgets.QTableWidgetItem(row[0]))
                        self.showCoursesTable.setItem(tableIndex,1,QtWidgets.QTableWidgetItem(row[1]))
                        self.showCoursesTable.setItem(tableIndex,2,QtWidgets.QTableWidgetItem(str(row[2])))
                        
                        tableIndex+=1




        # Problem Ends
                

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(" background-color: #345687;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(290, 10, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-size: 40px;\n"
"color: white;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(310, 80, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font-size: 30px;\n"
"color: white;")
        self.label_5.setObjectName("label_5")
        self.courseViewAllCoursesHomeButton = QtWidgets.QPushButton(self.frame)
        self.courseViewAllCoursesHomeButton.setGeometry(QtCore.QRect(10, 10, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.courseViewAllCoursesHomeButton.setFont(font)
        self.courseViewAllCoursesHomeButton.clicked.connect(self.home)
        self.courseViewAllCoursesHomeButton.setStyleSheet("background-color: white;\n"
"display: inline-block;\n"
"      padding: 10px 20px;\n"
"      font-size: 30px;\n"
"      text-align: center;\n"
"      text-decoration: none;\n"
"      cursor: pointer;\n"
"      border-radius: 5px;\n"
"      transition: background-color 0.3s ease;\n"
" border: 4px solid brown;")
        self.courseViewAllCoursesHomeButton.setObjectName("courseViewAllCoursesHomeButton")
        self.showCoursesTable = QtWidgets.QTableWidget(self.frame)
        self.showCoursesTable.setGeometry(QtCore.QRect(100, 170, 561, 351))
        self.showCoursesTable.setStyleSheet("background-color:white;")
        self.showCoursesTable.setObjectName("showCoursesTable")
        self.showCoursesTable.setColumnCount(3)
        self.showCoursesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.showCoursesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.showCoursesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.showCoursesTable.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "My College"))
        self.label_5.setText(_translate("MainWindow", "All Courses"))
        self.courseViewAllCoursesHomeButton.setText(_translate("MainWindow", "Home"))
        item = self.showCoursesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Course ID"))
        item = self.showCoursesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Course Name"))
        item = self.showCoursesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Course Credit Hrs."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.loadData()
    sys.exit(app.exec_())
