# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Designs/landingPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QVBoxLayout
from studentLandingPageUI import StudentLandingPageUI
import os
import platform
from PyQt5.uic import loadUi

class LandingPageUI(object):
        
        def clickStudentButton(self):
               os.system("python studentLandingPageUI.py") 

        def clickCourseButton(self):
                os.system("python courseLandingPageUI.py")
        
        def clickRegisterUnregisterButton(self):
                os.system("python registerunregisterLandingPageUI.py")
        
        

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(802, 615)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                

                self.centralwidget.setObjectName("centralwidget")
                self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
                self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 821, 651))
                self.gridLayoutWidget.setObjectName("gridLayoutWidget")
                self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
                self.gridLayout.setContentsMargins(0, 0, 0, 0)
                self.gridLayout.setObjectName("gridLayout")
                self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
                self.frame.setAutoFillBackground(False)
                self.frame.setStyleSheet(" background-color: #345687;")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.landingPageStudentButton = QtWidgets.QPushButton(self.frame)
                self.landingPageStudentButton.setGeometry(QtCore.QRect(150, 150, 341, 111))
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.landingPageStudentButton.setFont(font)
                self.landingPageStudentButton.clicked.connect(self.clickStudentButton)
                self.landingPageStudentButton.setStyleSheet("background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 30px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid green;")
                self.landingPageStudentButton.setObjectName("landingPageStudentButton")
                self.landingPageCourseButton = QtWidgets.QPushButton(self.frame)
                self.landingPageCourseButton.setGeometry(QtCore.QRect(150, 300, 341, 111))
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.landingPageCourseButton.setFont(font)
                self.landingPageCourseButton.clicked.connect(self.clickCourseButton)
                self.landingPageCourseButton.setStyleSheet(" background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 30px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid brown;")
                self.landingPageCourseButton.setObjectName("landingPageCourseButton")
                self.landingPageRegisterUnregisterButton = QtWidgets.QPushButton(self.frame)
                self.landingPageRegisterUnregisterButton.clicked.connect(self.clickRegisterUnregisterButton)
                self.landingPageRegisterUnregisterButton.setGeometry(QtCore.QRect(150, 450, 341, 111))
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.landingPageRegisterUnregisterButton.setFont(font)
                self.landingPageRegisterUnregisterButton.setStyleSheet(" background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 30px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid purple;")
                self.landingPageRegisterUnregisterButton.setObjectName("landingPageRegisterUnregisterButton")
                self.label = QtWidgets.QLabel(self.frame)
                self.label.setGeometry(QtCore.QRect(520, 150, 131, 111))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
                self.label.setSizePolicy(sizePolicy)
                self.label.setText("")
                self.label.setPixmap(QtGui.QPixmap("./student-with-graduation-cap.png"))
                self.label.setScaledContents(True)
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.frame)
                self.label_2.setGeometry(QtCore.QRect(520, 300, 131, 111))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
                self.label_2.setSizePolicy(sizePolicy)
                self.label_2.setText("")
                self.label_2.setPixmap(QtGui.QPixmap("./open-book.png"))
                self.label_2.setScaledContents(True)
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.frame)
                self.label_3.setGeometry(QtCore.QRect(520, 450, 131, 111))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
                self.label_3.setSizePolicy(sizePolicy)
                self.label_3.setText("")
                self.label_3.setPixmap(QtGui.QPixmap("./register.png"))
                self.label_3.setScaledContents(True)
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.frame)
                self.label_4.setGeometry(QtCore.QRect(300, 20, 211, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("font-size: 40px;\n"
        "color: white;")
                self.label_4.setObjectName("label_4")
                self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
                MainWindow.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "My College - Homepage"))
                # Set the window icon
                MainWindow.setWindowIcon(QIcon("./icon.png"))
                self.landingPageStudentButton.setText(_translate("MainWindow", "Student"))
                self.landingPageCourseButton.setText(_translate("MainWindow", "Course"))
                self.landingPageRegisterUnregisterButton.setText(_translate("MainWindow", "Register/Unregister"))
                self.label_4.setText(_translate("MainWindow", "My College"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = LandingPageUI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
