# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Designs/registerLandingPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyodbc
from PyQt5.QtWidgets import QMessageBox
from RegisterSuccessfullPageUI import registerSuccess
import os

class Ui_MainWindow(object):
    def home(self):
        os.system("python landingPageUI.py")
    def registerStudent(self):
        cID = self.registerLandingPageTakeCourseID.toPlainText() 
        sID = self.registerLandingPageTakeStudentID.toPlainText()
        if(cID and sID != ''):
                server = 'DESKTOP-03OJGVQ\SQLEXPRESS'
                database = 'myCollege'
                trusted_connection = 'yes'
                driver = '{ODBC Driver 17 for SQL Server}'  # Adjust the driver based on your SQL Server version

                        # Create a connection string
                connection_string = f"DRIVER={driver};SERVER={server};DATABASE={database};Trusted_Connection={trusted_connection}"

                        # Establish a connection
                with pyodbc.connect(connection_string) as connection:
                        cursor = connection.cursor()

                        query = f"SELECT COUNT(*) FROM Course WHERE courseID = ?"
                        result = cursor.execute(query, cID).fetchone()

                                # Check the result and update the label
                        if result[0] > 0:
                                        # Creating file to store ID
                                
                                cursor = connection.cursor()

                                query2 = f"SELECT COUNT(*) FROM Student WHERE studentID = ?"
                                result2 = cursor.execute(query2, sID).fetchone()
                                if result2[0] >0:
                                        query3= "INSERT INTO [dbo].[Assign_Course]([studentID],[courseID])VALUES(?,?)"
                                        cursor.execute(query3,sID,cID)
                                        connection.commit()
                                        print("Registered successfully.")
                                        self.window = QtWidgets.QMainWindow()
                                        self.ui = registerSuccess()
                                        self.ui.setupUi(self.window)
                                        self.window.show()
                                else:
                                        error_dialog = QMessageBox()
                                        error_dialog.setIcon(QMessageBox.Critical)
                                        error_dialog.setWindowTitle("Error")
                                        error_dialog.setText("Enter Valid Course ID Number.\nEnter Valid Student ID Number")
                                        error_dialog.setStandardButtons(QMessageBox.Ok)
                                        error_dialog.exec_()
                        else:
                                error_dialog = QMessageBox()
                                error_dialog.setIcon(QMessageBox.Critical)
                                error_dialog.setWindowTitle("Error")
                                error_dialog.setText("Enter Valid Course ID Number.\nEnter Valid Student ID Number")
                                error_dialog.setStandardButtons(QMessageBox.Ok)
                                error_dialog.exec_()

                                


                connection.close()

                        
                        
        else:
                        # Create an error QMessageBox
                error_dialog = QMessageBox()
                error_dialog.setIcon(QMessageBox.Critical)
                error_dialog.setWindowTitle("Error")
                error_dialog.setText("Enter Valid Course ID Number.\nEnter Valid Student ID Number")
                error_dialog.setStandardButtons(QMessageBox.Ok)

                        # Show the error dialog
                error_dialog.exec_()


    def clearButton(self):
        self.registerLandingPageTakeCourseID.clear()
        self.registerLandingPageTakeStudentID.clear()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(" background-color: #345687;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(290, 10, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-size: 40px;\n"
"color: white;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(330, 90, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font-size: 30px;\n"
"color: white;")
        self.label_5.setObjectName("label_5")
        self.registerLandingPageTakeCourseID = QtWidgets.QTextEdit(self.frame)
        self.registerLandingPageTakeCourseID.setGeometry(QtCore.QRect(370, 210, 301, 41))
        self.registerLandingPageTakeCourseID.setStyleSheet("background-color:white;color:black;font-size:25px;")
        self.registerLandingPageTakeCourseID.setObjectName("registerLandingPageTakeCourseID")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(130, 210, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(-1)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font-size: 30px;\n"
"color: white;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(130, 280, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(-1)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font-size: 30px;\n"
"color: white;")
        self.label_7.setObjectName("label_7")
        self.registerLandingPageTakeStudentID = QtWidgets.QTextEdit(self.frame)
        self.registerLandingPageTakeStudentID.setGeometry(QtCore.QRect(370, 280, 301, 41))
        self.registerLandingPageTakeStudentID.setStyleSheet("background-color:white;color:black;font-size:25px;")
        self.registerLandingPageTakeStudentID.setObjectName("registerLandingPageTakeStudentID")
        self.registerLandingPageSubmitButton = QtWidgets.QPushButton(self.frame)
        self.registerLandingPageSubmitButton.setGeometry(QtCore.QRect(430, 410, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.registerLandingPageSubmitButton.setFont(font)
        self.registerLandingPageSubmitButton.setStyleSheet("background-color: white;\n"
"display: inline-block;\n"
"      padding: 10px 20px;\n"
"      font-size: 20px;\n"
"      text-align: center;\n"
"      text-decoration: none;\n"
"      cursor: pointer;\n"
"      border-radius: 5px;\n"
"      transition: background-color 0.3s ease;\n"
" border: 4px solid green;")
        self.registerLandingPageSubmitButton.setObjectName("registerLandingPageSubmitButton")
        self.registerLandingPageSubmitButton.clicked.connect(self.registerStudent)
        self.registerLandingPageClearButton = QtWidgets.QPushButton(self.frame)
        self.registerLandingPageClearButton.setGeometry(QtCore.QRect(240, 410, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.registerLandingPageClearButton.setFont(font)
        self.registerLandingPageClearButton.clicked.connect(self.clearButton)
        self.registerLandingPageClearButton.setStyleSheet("background-color: white;\n"
"display: inline-block;\n"
"      padding: 10px 20px;\n"
"      font-size: 20px;\n"
"      text-align: center;\n"
"      text-decoration: none;\n"
"      cursor: pointer;\n"
"      border-radius: 5px;\n"
"      transition: background-color 0.3s ease;\n"
" border: 4px solid red;")
        self.registerLandingPageClearButton.setObjectName("registerLandingPageClearButton")
        self.registerLandingPageHomeButton = QtWidgets.QPushButton(self.frame)
        self.registerLandingPageHomeButton.clicked.connect(self.home)
        self.registerLandingPageHomeButton.setGeometry(QtCore.QRect(10, 10, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.registerLandingPageHomeButton.setFont(font)
        self.registerLandingPageHomeButton.setStyleSheet("background-color: white;\n"
"display: inline-block;\n"
"      padding: 10px 20px;\n"
"      font-size: 30px;\n"
"      text-align: center;\n"
"      text-decoration: none;\n"
"      cursor: pointer;\n"
"      border-radius: 5px;\n"
"      transition: background-color 0.3s ease;\n"
" border: 4px solid green;")
        self.registerLandingPageHomeButton.setObjectName("registerLandingPageHomeButton")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "My College"))
        self.label_5.setText(_translate("MainWindow", "Register"))
        self.label_6.setText(_translate("MainWindow", "Course ID"))
        self.label_7.setText(_translate("MainWindow", "Student ID"))
        self.registerLandingPageSubmitButton.setText(_translate("MainWindow", "Submit"))
        self.registerLandingPageClearButton.setText(_translate("MainWindow", "Clear"))
        self.registerLandingPageHomeButton.setText(_translate("MainWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
