# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Designs/studentLandingPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from PyQt5.QtGui import QIcon 

import os

from addStudentLandingPageUI import AddStudentLandingPage
from updateStudentLandingPageUI import UpdateStudentLandingPage

class StudentLandingPageUI(object):
        
        def homeButtonPressed(self):
                os.system("python landingPageUI.py")
        
        def addStudentPressed(self,MainWindow):
                os.system("python addStudentLandingPageUI.py")
                
        
        def updateStudentPressed(self):
                os.system("python updateStudentLandingPageUI.py")

        def viewStudents(self):
               os.system("python viewStudentsPageUI.py")
                

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(800, 613)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
                self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 801, 601))
                self.gridLayoutWidget.setObjectName("gridLayoutWidget")
                self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
                self.gridLayout.setContentsMargins(0, 0, 0, 0)
                self.gridLayout.setObjectName("gridLayout")
                self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
                self.frame.setStyleSheet("\n"
        "background-color: #345687;\n"
        "")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.label_4 = QtWidgets.QLabel(self.frame)
                self.label_4.setGeometry(QtCore.QRect(300, 10, 211, 51))
                font = QtGui.QFont()
                font.setFamily("Papyrus")
                font.setPointSize(-1)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("font-size: 40px;\n"
        "color: white;")
                self.label_4.setObjectName("label_4")
                self.studentLandingPageAddStudentButton = QtWidgets.QPushButton(self.frame)
                self.studentLandingPageAddStudentButton.setGeometry(QtCore.QRect(240, 150, 341, 111))
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.studentLandingPageAddStudentButton.setFont(font)
                self.studentLandingPageAddStudentButton.clicked.connect(self.addStudentPressed)
                self.studentLandingPageAddStudentButton.setStyleSheet("background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 30px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid green;")
                self.studentLandingPageAddStudentButton.setObjectName("studentLandingPageAddStudentButton")
                self.studentLandingPageUpdateStudent = QtWidgets.QPushButton(self.frame)
                self.studentLandingPageUpdateStudent.clicked.connect(self.updateStudentPressed)
                self.studentLandingPageUpdateStudent.setGeometry(QtCore.QRect(240, 290, 341, 111))
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.studentLandingPageUpdateStudent.setFont(font)
                self.studentLandingPageUpdateStudent.setStyleSheet("background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 30px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid green;")
                self.studentLandingPageUpdateStudent.setObjectName("studentLandingPageUpdateStudent")
                self.studentLandingPageViewStudentButton = QtWidgets.QPushButton(self.frame)
                self.studentLandingPageViewStudentButton.setGeometry(QtCore.QRect(240, 430, 341, 111))
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.studentLandingPageViewStudentButton.setFont(font)
                self.studentLandingPageViewStudentButton.clicked.connect(self.viewStudents)
                self.studentLandingPageViewStudentButton.setStyleSheet("background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 30px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid green;")
                self.studentLandingPageViewStudentButton.setObjectName("studentLandingPageViewStudentButton")
                self.studentLandingPageHomeButton = QtWidgets.QPushButton(self.frame)
                self.studentLandingPageHomeButton.setGeometry(QtCore.QRect(10, 10, 141, 61))

                self.studentLandingPageHomeButton.clicked.connect(self.homeButtonPressed)
                
                font = QtGui.QFont()
                font.setFamily("Comic Sans MS")
                font.setPointSize(-1)
                font.setUnderline(False)
                font.setStrikeOut(False)
                self.studentLandingPageHomeButton.setFont(font)
                self.studentLandingPageHomeButton.setStyleSheet("background-color: white;\n"
        "display: inline-block;\n"
        "      padding: 10px 20px;\n"
        "      font-size: 30px;\n"
        "      text-align: center;\n"
        "      text-decoration: none;\n"
        "      cursor: pointer;\n"
        "      border-radius: 5px;\n"
        "      transition: background-color 0.3s ease;\n"
        " border: 4px solid green;")
                self.studentLandingPageHomeButton.setObjectName("studentLandingPageHomeButton")
                self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
                MainWindow.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "My College - Student Section"))
                MainWindow.setWindowIcon(QIcon("./icon.png"))
                self.label_4.setText(_translate("MainWindow", "My College"))
                self.studentLandingPageAddStudentButton.setText(_translate("MainWindow", "Add Student"))
                self.studentLandingPageUpdateStudent.setText(_translate("MainWindow", "Update Student"))
                self.studentLandingPageViewStudentButton.setText(_translate("MainWindow", "View Student"))
                self.studentLandingPageHomeButton.setText(_translate("MainWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = StudentLandingPageUI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
