# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Designs/updateCourseNameUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import pyodbc
from PyQt5.QtWidgets import QMessageBox
from updateSuccessfullyPageUI import UpdateSuccessfullPage
import os

class Ui_MainWindow(object):
    def home(self):
        os.system("python landingPageUI.py")
    def updtePressed(self):
        name = self.updateCourseNameTakeCourseName.toPlainText()
        if(name!=''):
                server = 'DESKTOP-03OJGVQ\SQLEXPRESS'
                database = 'myCollege'
                trusted_connection = 'yes'
                driver = '{ODBC Driver 17 for SQL Server}'  # Adjust the driver based on your SQL Server version

                        # Create a connection string
                connection_string = f"DRIVER={driver};SERVER={server};DATABASE={database};Trusted_Connection={trusted_connection}"

                with open("DataCourse.txt","r") as file:
                        id = file.read()
                        file.close()        
                        # Establish a connection
                with pyodbc.connect(connection_string) as connection:
                        cursor = connection.cursor()
                        value1 = id
                        value2 = name
                                # Use parameterized query to prevent SQL injection
                        insert_query = f"UPDATE Course SET courseName = (?) WHERE courseID = (?)"
                        cursor.execute(insert_query,value2,value1)
                        print(insert_query)
                        connection.commit()
                self.window = QtWidgets.QMainWindow()
                self.ui = UpdateSuccessfullPage()
                self.ui.setupUi(self.window)
                self.window.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 591))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(" background-color: #345687;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(290, 10, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-size: 40px;\n"
"color: white;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(250, 120, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font-size: 30px;\n"
"color: white;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(130, 250, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(-1)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font-size: 30px;\n"
"color: white;")
        self.label_6.setObjectName("label_6")
        self.updateCourseNameHomeButton = QtWidgets.QPushButton(self.frame)
        self.updateCourseNameHomeButton.clicked.connect(self.home)
        self.updateCourseNameHomeButton.setGeometry(QtCore.QRect(10, 10, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.updateCourseNameHomeButton.setFont(font)
        self.updateCourseNameHomeButton.setStyleSheet("background-color: white;\n"
"display: inline-block;\n"
"      padding: 10px 20px;\n"
"      font-size: 30px;\n"
"      text-align: center;\n"
"      text-decoration: none;\n"
"      cursor: pointer;\n"
"      border-radius: 5px;\n"
"      transition: background-color 0.3s ease;\n"
" border: 4px solid brown;")
        self.updateCourseNameHomeButton.setObjectName("updateCourseNameHomeButton")
        self.updateCourseNameUpdateButton = QtWidgets.QPushButton(self.frame)
       
        self.updateCourseNameUpdateButton.clicked.connect(self.updtePressed)
        self.updateCourseNameUpdateButton.setGeometry(QtCore.QRect(310, 340, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.updateCourseNameUpdateButton.setFont(font)
        self.updateCourseNameUpdateButton.setStyleSheet("background-color: white;\n"
"display: inline-block;\n"
"      padding: 10px 20px;\n"
"      font-size: 30px;\n"
"      text-align: center;\n"
"      text-decoration: none;\n"
"      cursor: pointer;\n"
"      border-radius: 5px;\n"
"      transition: background-color 0.3s ease;\n"
" border: 4px solid brown;")
        self.updateCourseNameUpdateButton.setObjectName("updateCourseNameUpdateButton")
        self.updateCourseNameTakeCourseName = QtWidgets.QTextEdit(self.frame)
        self.updateCourseNameTakeCourseName.setGeometry(QtCore.QRect(400, 250, 301, 41))
        self.updateCourseNameTakeCourseName.setStyleSheet("background-color:white;color:black;font-size:25px;")
        self.updateCourseNameTakeCourseName.setObjectName("updateCourseNameTakeCourseName")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "My College"))
        self.label_5.setText(_translate("MainWindow", "Update Course Name"))
        self.label_6.setText(_translate("MainWindow", "Course Name"))
        self.updateCourseNameHomeButton.setText(_translate("MainWindow", "Home"))
        self.updateCourseNameUpdateButton.setText(_translate("MainWindow", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
